import type { Metadata } from "next";
import { inter, sevillana } from "../fonts"
import "./global.css";



export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  header,
  children,
}: Readonly<{
  header:React.ReactNode;
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body className={`${inter.variable} ${sevillana.variable}`}>
        {header}
        {children}
        
        </body>
    </html>
  );
}
